service: serverless-api

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000
    lambdaTimeout: 30

functions:
  hello:
    handler: src/handler/handler.main
    events:
      - http:
          path: hello
          method: get
      - http:
          path: goodbye
          method: get
      - http:
          path: data
          method: post
      - http:
          path: find-by-phone
          method: get     
  openai:
    handler: src/openai/openai.handler
    timeout: 30
    events:
      - http:
          path: openai
          method: get
      - http:
          path: openai
          method: post          
